/* Every user-facing string in the superadmin console, in one place — same
   pattern as components/studio/copy.ts and components/coach/copy.ts.
   CLAUDE.md Iron Rule: no hardcoded user-facing strings in components. */

export const copy = {
  chromeTitle: 'Platform operations',

  tabs: {
    label: 'Superadmin sections',
    overview: 'Overview',
    studios: 'Studios & staff',
  },

  dashboard: {
    platformHeading: 'Platform, last 7 days',
    sessionsToday: 'Sessions today',
    sessionsThisWeek: 'Sessions this week',
    revenue7d: 'Earned, last 7 days',
    revenueUnit: 'AED',
    activeCoaches: 'Active coaches',
    bySiteHeading: 'By studio',
    bySiteSubtitle: 'Same numbers, split per site.',
    colSite: 'Studio',
    colSessionsToday: 'Sessions today',
    colSessionsWeek: 'Sessions this week',
    colRevenue: 'AED, 7d',
    colCoaches: 'Active coaches',
    empty: 'No studios yet — create one in Studios & staff.',
  },

  workload: {
    heading: 'Coach workload',
    subtitle: 'Next 7 days scheduled, last 7 days completed.',
    empty: 'No coaches to show yet.',
    colName: 'Coach',
    colSite: 'Studio',
    colShiftHours: 'Shift hrs, next 7d',
    colBookedHours: 'Booked hrs, next 7d',
    colUpcoming: 'Upcoming bookings',
    colCompleted: 'Completed, last 7d',
  },

  ledger: {
    heading: 'Cash ledger',
    subtitle: 'Booking revenue plus manual entries — walk-ins, refunds, adjustments.',
    empty: 'Nothing recorded yet.',
    colDate: 'Date',
    colSite: 'Studio',
    colType: 'Type',
    colNote: 'Note',
    colAed: 'AED',
    total: 'Total',
    type: {
      booking_revenue: 'Booking revenue',
      manual_in: 'Cash in',
      manual_out: 'Cash out',
    },
    entryHeading: 'Record a cash entry',
    site: 'Studio',
    entryType: 'Type',
    amount: 'Amount (AED)',
    note: 'Note (optional)',
    submit: 'Record entry',
    recorded: 'Cash entry recorded.',
  },

  studios: {
    sitesHeading: 'Studios',
    sitesSubtitle: 'Every site on the platform.',
    sitesEmpty: 'No studios yet — create the first one.',
    colName: 'Name',
    colCity: 'City',
    createHeading: 'Create a studio',
    name: 'Studio name',
    city: 'City',
    createSubmit: 'Create studio',
    created: 'Studio created.',

    staffHeading: 'Staff across all studios',
    staffSubtitle: 'Coaches and studio managers, every site.',
    staffEmpty: 'No staff yet.',
    colStaffName: 'Name',
    colRole: 'Role',
    colSite: 'Studio',
    colAction: 'Action',
    reassign: 'Reassign',
    reassignHeading: 'Move to studio',
    reassignSubmit: 'Move',
    reassigned: 'Staff member reassigned.',

    createStaffHeading: 'Create a staff account',
    createStaffSubtitle: 'A coach or studio manager, at any studio.',
    fullName: 'Full name',
    email: 'Email',
    password: 'Temporary password',
    passwordHelper: 'At least 8 characters. Hand it to them in person.',
    role: 'Role',
    roleCoach: 'Coach',
    roleStudioManager: 'Studio manager',
    site: 'Studio',
    createStaffSubmit: 'Create account',
    staffCreated: 'Staff account created.',
  },
};
